apiVersion: v1
kind: Pod
metadata:
  name: file-server-pod
spec:
  containers:
  - name: file-server
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: file-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: file-storage
    hostPath:
      path: /path/to/your/files
      type: Directory

